routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/admin', 'AdminController@index')->name('admin')->middleware('admin');
Route::get('/operator', 'OperatorController@index')->name('operator')->middleware('operator');
Route::get('/lapor', 'LaporController@index')->name('lapor')->middleware('lapor');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("users", "UserController");

Route::get('/subdistricts/trash', 'SubdistrictController@trash')->name('subdistricts.trash');
Route::get('/subdistricts/{id}/restore', 'SubdistrictController@restore')->name('subdistricts.restore');
Route::delete('/subdistricts/{id}/delete-permanent','SubdistrictController@deletePermanent')->name('subdistricts.delete-permanent');
Route::get('/ajax/subdistricts/search','SubdistrictController@ajaxSearch');
Route::resource("subdistricts", "SubdistrictController");

Route::get('/cari', 'Select2Controller@loadData');
Route::get('/villages/trash', 'VillageController@trash')->name('villages.trash');
Route::get('/villages/{id}/restore', 'VillageController@restore')->name('villages.restore');
Route::delete('/villages/{id}/delete-permanent','VillageController@deletePermanent')->name('villages.delete-permanent');
Route::resource('villages', 'VillageController');

Route::get('/floodreports/trash', 'FloodreportController@trash')->name('floodreports.trash');
Route::get('/floodreports/{id}/restore', 'FloodreportController@restore')->name('floodreports.restore');
Route::delete('/floodreports/{id}/delete-permanent','FloodreportController@deletePermanent')->name('floodreports.delete-permanent');
Route::resource('floodreports', 'FloodreportController');

Route::get('/helpreports/trash', 'HelpreportController@trash')->name('helpreports.trash');
Route::get('/helpreports/{id}/restore', 'HelpreportController@restore')->name('helpreports.restore');
Route::delete('/helpreports/{id}/delete-permanent','HelpreportController@deletePermanent')->name('helpreports.delete-permanent');
Route::resource('helpreports', 'HelpreportController');

Route::get('/floodhistories/trash', 'FloodhistoryController@trash')->name('floodhistories.trash');
Route::get('/floodhistories/{id}/restore', 'FloodhistoryController@restore')->name('floodhistories.restore');
Route::delete('/floodhistories/{id}/delete-permanent','FloodhistoryController@deletePermanent')->name('floodhistories.delete-permanent');
Route::resource('floodhistories', 'FloodhistoryController');

Route::get('/posts/trash', 'PostController@trash')->name('posts.trash');
Route::get('/posts/{id}/restore', 'PostController@restore')->name('posts.restore');
Route::delete('/posts/{id}/delete-permanent','PostController@deletePermanent')->name('posts.delete-permanent');
Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Post extends Model
{
    protected $table = 'posts';

    use SoftDeletes;

    public function village(){
        return $this->belongsTo('App\Village');
    }
    
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{

    public function action(){

        $data = Post::all();

        $params = [
            'code' => 201,
            'message' => 'Get Posko Evakuasi Success!',
            'dataposko' => $data,
        ];
        return response()->json($params);

    }

    public function requestPosko(Request $request){

        $latawal=$request->latawal;
        $longawal=$request->longawal;

        $dataposko = Post::all();

        foreach ($dataposko as $item){
            $theta = $longawal-(float)$item->longitude;
            $miles = (sin(deg2rad($latawal)) * sin(deg2rad($item->latitude))) + (cos(deg2rad($latawal)) * cos(deg2rad($item->latitude)) * cos(deg2rad($theta)));
            $miles = acos($miles);
            $miles = rad2deg($miles);
            $miles = $miles * 60 * 1.1515;
            $kilometers = $miles * 1.609344;
            $data[]=[
                'nama_posko'=>$item->name,
                'latitude'=>$item->latitude,
                'longitude'=>$item->longitude,
                'jarak'=>$kilometers,
                'deskripsi'=>$item->deskripsi
            ];
        }

        foreach ($data as $key=>$item2){
            $jarakdata[]=[$item2["jarak"]];
            $jarakmin=min($jarakdata);
        }

        foreach ($data as $item3){
            if($item3["jarak"]==$jarakmin[0]){
                $data2[]=[
                    'name'=>$item3["nama_posko"],
                    'latitude'=>$item3["latitude"],
                    'longitude'=>$item3["longitude"],
                    'jarak'=>$item3["jarak"],
                    'deskripsi'=>$item3["deskripsi"]
                ];
            }
        }

        $params = [
            'code' => 200,
            'message' => 'Get Posko Evakuasi Success!',
            'jarak' => $jarakmin[0],
            'posko' => $data2,
        ];
        return response()->json($params);

    }
    

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class PostController extends Controller
{

    public function __construct(){
        $this->middleware(function($request, $next){
            if(Gate::allows('manage-admin')) return $next($request);
            abort(403, 'Anda tidak memiliki cukup hak akses');
            });
        }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = \App\Post::paginate(10);

        return view('posts.index', ['posts' => $posts]);
 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $villages = \App\Village::all();

        $params=[
            'village'=>$villages
        ];
        return view('posts.create',$params);
  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = \Validator::make($request->all(),[
            "name" => "required",
            "alamat" => "required",
            "deskripsi" => "required",
            "latitude" => "required",
            "longitude" => "required",
            ])->validate();

        $maxId = \App\Post::max('id');
        $new_post = new \App\Post;
        $new_post->id = $maxId + 1;
        $new_post->name = $request->get('name');
        $new_post->alamat = $request->get('alamat');
        $new_post->deskripsi = $request->get('deskripsi');
        
        $new_post->latitude = $request->get('latitude');
        $new_post->longitude = $request->get('longitude');

        $new_post->created_by = \Auth::user()->id;
        $new_post->village_id=$request->villages ;
        $new_post->save();

        return redirect()->route('posts.index')->with('status', 'Data post telah berhasil ditambahkan');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = \App\Post::findOrFail($id);

        return view('posts.show', ['post' => $post]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $villages = \App\Village::all();
        
        $params=[
            'village'=>$villages
        ];

        $post_to_edit = \App\Post::findOrFail($id);
        
        return view('posts.edit', ['post' => $post_to_edit],$params);
  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = \App\Post::findOrFail($id);

        $post->name = $request->get('name');
        $post->alamat = $request->get('alamat');
        $post->deskripsi = $request->get('deskripsi');
        $post->latitude = $request->get('latitude');
        $post->longitude = $request->get('longitude');
     
        $new_foto = $request->file('foto');

        if($new_foto){
            if($post->foto && file_exists(storage_path('app/public/' . $post->foto))){
            \Storage::delete('public/'. $post->foto);
        }
        $new_foto_path = $new_foto->store('post-fotos', 'public');
        
        $post->foto = $new_foto_path;
        }

        $post->updated_by = \Auth::user()->id;
        $post->village_id=$request->villages ;

        $post->save();

        return redirect()->route('posts.index', ['id'=>$post->id])->with('status', 'Data posko telah berhasil diperbarui');
 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = \App\Post::findOrFail($id);

        $post->delete();

        return redirect()->route('posts.index')->with('status', 'Data post telah diarsipkan');
  
    }

    public function trash(){
        $deleted_post = \App\Post::onlyTrashed()->paginate(10);
        
        return view('posts.trash', ['posts' => $deleted_post]);
    }

    public function restore($id){
        $post = \App\Post::withTrashed()->findOrFail($id);
        
        if($post->trashed()){
            $post->restore();
        } else {
            return redirect()->route('posts.index')->with('status', 'Data post tidak ada di tabel arsip');
        }

        return redirect()->route('posts.index')->with('status', 'Data post telah berhasil direstore');
    }

    public function deletePermanent($id){
        $post = \App\Post::withTrashed()->findOrFail($id);
        
        if(!$post->trashed()){
            return redirect()->route('posts.index')->with('status', 'Data post aktif, Tidak bisa hapus permanen!');
        } else {
            $post->forceDelete();
            return redirect()->route('posts.index')->with('status', 'Data post telah berhasil dihapus permanen');
        }
    }
}

resources/views/posts/create.blade.php
@extends("layouts.global")
@section("title") Tambah Data Posko @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10" action="{{route('posts.store')}}"
            method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <div class="form-group">
                    <label for="name">Nama Posko</label>
                    <input value="{{old('name')}}" class="form-control {{$errors->first('name') ? "is-invalid" : ""}}"
                        placeholder="Masukkan nama posko" type="text" name="name" id="name" />
                    <div class="invalid-feedback">
                        {{$errors->first('name')}}
                    </div>    
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat Posko </label>
                    <input value="{{old('alamat')}}" class="form-control {{$errors->first('alamat') ? "is-invalid" : ""}}"
                        placeholder="Masukkan alamat posko" type="text" name="alamat" id="alamat" />
                    <div class="invalid-feedback">
                        {{$errors->first('alamat')}}
                    </div>  
                </div>
                <div class="form-group">
                    <label for="villages">Desa</label><br>
                    <select name="villages" class="form-control">
                        @foreach($village as $key =>$item)
                        <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="deskripsi">Deskripsi</label>
                    <input value="{{old('deskripsi')}}" class="form-control {{$errors->first('deskripsi') ? "is-invalid" : ""}}"
                        placeholder="Masukkan deskripsi" type="text" name="deskripsi" id="deskripsi" />
                    <div class="invalid-feedback">
                        {{$errors->first('deskripsi')}}
                    </div> 
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                        <input value="{{old('latitude')}}" class="form-control {{$errors->first('latitude') ? "is-invalid" : ""}}"
                        placeholder="Masukkan posisi latitude posko" type="text" name="latitude" id="latitude" />
                    <div class="invalid-feedback">
                        {{$errors->first('latitude')}}
                    </div>   
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                        <input value="{{old('longitude')}}" class="form-control {{$errors->first('longitude') ? "is-invalid" : ""}}"
                        placeholder="Masukkan posisi longitude posko" type="text" name="longitude" id="longitude" />
                    <div class="invalid-feedback">
                        {{$errors->first('longitude')}}
                    </div> 
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/posts/edit.blade.php
@extends("layouts.global")
@section("title") Edit Data Posko @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10"
            action="{{route('posts.update', ['post'=>$post->id])}}" method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <input type="hidden" value="PUT" name="_method">
                <div class="form-group">
                    <label for="name">Nama Posko</label>
                    <input value="{{$post->name}}" type="text" class="form-control" id="name" name="name"
                        placeholder="Masukkan nama posko">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat Posko</label>
                    <input value="{{$post->alamat}}" type="text" class="form-control" id="alamat" name="alamat"
                        placeholder="Masukkan Alamat">
                </div>
                <div class="form-group">
                    <label for="villages">Desa</label><br>
                    <select name="villages" class="form-control">
                        @foreach($village as $key =>$item)
                        <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="deskripsi">Deskripsi</label>
                    <input value="{{$post->deskripsi}}" type="text" class="form-control" id="deskripsi" name="deskripsi"
                        placeholder="Masukkan deskripsi posko">
                </div> 
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input value="{{$post->latitude}}" type="text" class="form-control" id="latitude" name="latitude"
                        placeholder="Masukkan posisi latitude Desa">
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input value="{{$post->longitude}}" type="text" class="form-control" id="longitude"
                        name="longitude" placeholder="Masukkan posisi longitude Desa">
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Edit</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/posts/index.blade.php
@extends("layouts.global")
@section("title") Data Posko @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Data Posko</h1>
            </div><br><br>
            <div class="col-sm-10">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item active"><a href="{{route('posts.index')}}">Data Aktif</a></li>
                    <li class="breadcrumb-item"><a href="{{route('posts.trash')}}">Data Arsip</a></li>
                </ol>
            </div>
            <div class="col-sm-2 text-right">
                <a href="{{route('posts.create')}}" class="btn btn-primary btn-sm">Tambah</a>
            </div>
        </div>
        @if(session('status'))
        <div class="alert">
            {{session('status')}}
        </div>
        @endif
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th><b>Nama Posko</b></th>
                                    <th><b>Alamat</b></th>
                                    <th><b>Desa</b></th>
                                    <th><b>Kecamatan</b></th>
                                    <th><b>Opsi</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $post)
                                <tr>
                                    <td>{{$post->name}}</td>
                                    <td>{{$post->alamat}}</td>
                                    <td>{{$post->village['name']}}</td>
                                    <td>{{$post->village->subdistrict['name']}}</td>
                                    <td>
                                        <a class="btn btn-primary btn-sm"
                                            href="{{route('posts.edit',['post'=>$post->id])}}">Edit</a>
                                        <a class="btn btn-success btn-sm"
                                            href="{{route('posts.show',['post'=>$post->id])}}">Info</a>
                                        <form
                                            onsubmit="return confirm('Apakah Anda yakin ingin mengarsipkan data ini ?')"
                                            class="d-inline" action="{{route('posts.destroy', ['post' => $post->id ])}}"
                                            method="POST">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="submit" value="Arsip" class="btn btn-warning btn-sm">
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colSpan="10">
                                        {{$posts->appends(Request::all())->links()}}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/posts/show.blade.php
@extends("layouts.global")
@section("title") Detail Posko @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Posko {{$post->name}}</h1>
            </div><br><br>

        </div>
        @if(session('status'))
        <div class="alert">
            {{session('status')}}
        </div>
        @endif
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="card col-6 ">
            <div class="row col-12">
                <div class="col-sm-6 ">
                    <label>Deskripsi</label>
                </div>
                <div class="col-sm-6 ">
                    <label>{{$post->deskripsi}}</label>
                </div>            
               <div class="col-sm-6 ">
                    <label>Latitude</label>
                </div>
                <div class="col-sm-6 ">
                    <label>{{$post->latitude}}</label>
                </div>
                <div class="col-sm-6 ">
                    <label>Longitude</label>
                </div>
                <div class="col-sm-6 ">
                    <label>{{$post->longitude}}</label>
                </div>
            </div><br>
        </div>
    </div>
</section>
@endsection

resources/views/posts/trash.blade.php
@extends("layouts.global")
@section("title") Data Arsip Posko @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Data Posko</h1>
            </div><br><br>
            <div class="col-sm-10">
            <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item "><a href="{{route('floodhistories.index')}}">Data Aktif</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('floodhistories.trash')}}">Data Arsip</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">

                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th><b>Nama Posko</b></th>
                                    <th><b>Alamat</b></th>
                                    <th><b>Desa</b></th>
                                    <th><b>Kecamatan</b></th>
                                    <th><b>Deskripsi</b></th>
                                    <th><b>Latitude</b></th>
                                    <th><b>Longitude</b></th>
                                    <th><b>Opsi</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $post)
                                <tr>
                                    <td>{{$post->name}}</td>
                                    <td>{{$post->alamat}}</td>
                                    <td>{{$post->village['name']}}</td>
                                    <td>{{$post->village->subdistrict['name']}}</td>
                                    <td>{{$post->deskripsi}}</td>
                                    <th><b>{{$post->latitude}}</b></th>
                                    <th><b>{{$post->longitude}}</b></th>
                                    <td>
                                        <a href="{{route('posts.restore', ['id' => $post->id])}}"
                                            class="btn btn-success btn-sm">Restore</a>
                                        <form class="d-inline"
                                            action="{{route('posts.delete-permanent', ['id' => $post->id])}}"
                                            method="POST"
                                            onsubmit="return confirm('Apakah Anda yakin ingin menghapus data ini secara permanen?')">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <input type="submit" class="btn btn-danger btn-sm" value="Delete" />
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colSpan="10">
                                        {{$posts->appends(Request::all())->links()}}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
@endsection