routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/admin', 'AdminController@index')->name('admin')->middleware('admin');
Route::get('/operator', 'OperatorController@index')->name('operator')->middleware('operator');
Route::get('/lapor', 'LaporController@index')->name('lapor')->middleware('lapor');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("users", "UserController");

Route::get('/subdistricts/trash', 'SubdistrictController@trash')->name('subdistricts.trash');
Route::get('/subdistricts/{id}/restore', 'SubdistrictController@restore')->name('subdistricts.restore');
Route::delete('/subdistricts/{id}/delete-permanent','SubdistrictController@deletePermanent')->name('subdistricts.delete-permanent');
Route::get('/ajax/subdistricts/search','SubdistrictController@ajaxSearch');
Route::resource("subdistricts", "SubdistrictController");

Route::get('/cari', 'Select2Controller@loadData');
Route::get('/villages/trash', 'VillageController@trash')->name('villages.trash');
Route::get('/villages/{id}/restore', 'VillageController@restore')->name('villages.restore');
Route::delete('/villages/{id}/delete-permanent','VillageController@deletePermanent')->name('villages.delete-permanent');
Route::resource('villages', 'VillageController');

Route::get('/floodreports/trash', 'FloodreportController@trash')->name('floodreports.trash');
Route::get('/floodreports/{id}/restore', 'FloodreportController@restore')->name('floodreports.restore');
Route::delete('/floodreports/{id}/delete-permanent','FloodreportController@deletePermanent')->name('floodreports.delete-permanent');
Route::resource('floodreports', 'FloodreportController');

Route::get('/helpreports/trash', 'HelpreportController@trash')->name('helpreports.trash');
Route::get('/helpreports/{id}/restore', 'HelpreportController@restore')->name('helpreports.restore');
Route::delete('/helpreports/{id}/delete-permanent','HelpreportController@deletePermanent')->name('helpreports.delete-permanent');
Route::resource('helpreports', 'HelpreportController');

Route::get('/floodhistories/trash', 'FloodhistoryController@trash')->name('floodhistories.trash');
Route::get('/floodhistories/{id}/restore', 'FloodhistoryController@restore')->name('floodhistories.restore');
Route::delete('/floodhistories/{id}/delete-permanent','FloodhistoryController@deletePermanent')->name('floodhistories.delete-permanent');
Route::resource('floodhistories', 'FloodhistoryController');

Route::get('/posts/trash', 'PostController@trash')->name('posts.trash');
Route::get('/posts/{id}/restore', 'PostController@restore')->name('posts.restore');
Route::delete('/posts/{id}/delete-permanent','PostController@deletePermanent')->name('posts.delete-permanent');
Route::resource('posts', 'PostController');

app/HelpReport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class HelpReport extends Model
{
    protected $table = 'helpreports';

    use SoftDeletes;

    public function user(){
        return $this->belongsTo('App\User');
    }

    protected $fillable = [
        'user_id','tanggal', 'alamat', 'jenis_kerusakan', 'jenis_bantuan', 'telepon', 'keterangan','foto', 'latitude', 'longitude', 'status'
    ];
    
}

app/Http/Controllers/Api/HelpReportController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\HelpReport;
use App\User;


class HelpReportController extends Controller
{
    public function action (Request $request)
    {   
        $this->validate($request, [
            'tanggal' => 'required',
            'alamat' => 'required',
            'jenis_kerusakan' => 'required',
            'jenis_bantuan' => 'required',
            'telepon' => 'required',
            'keterangan' => 'required',
            'foto' => 'required|image',
        ]);

        $helpreport = HelpReport::create([
            'user_id' => auth()->user()->id, 
            'tanggal' => $request->tanggal,
            'alamat' => $request->alamat,
            'jenis_kerusakan' => $request->jenis_kerusakan,
            'jenis_bantuan' => $request->jenis_bantuan,
            'telepon' => $request->telepon,
            'keterangan' => $request->keterangan,
            'foto' => $request->file('foto')->store('helpreport-fotos'),
            'latitude' => $request->latitude,
            'longitude' => $request->longitude,
            'status' => "BARU",
        ]);


        return response()->json([
            "data" => $helpreport,
            "message" => "Laporan berhasil ditambahkan"
        ], 201);
    }
}

app/Http/Controllers/HelpReportController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class HelpReportController extends Controller
{

    public function __construct(){
        $this->middleware(function($request, $next){
            if(Gate::allows('manage-operator')) return $next($request);
            abort(403, 'Anda tidak memiliki cukup hak akses');
            });
        }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $status = $request->get('status');

        $keyword = $request->get('keyword') ? $request->get('keyword') : '';
        
        if($status){
            $helpreports = \App\Helpreport::where('status', strtoupper($status))->paginate(10);
        } else {
            $helpreports = \App\Helpreport::paginate(10);
        }

        return view('helpreports.index', ['helpreports' => $helpreports]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      
        return view('helpreports.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_helpreport = new \App\Helpreport;
        $new_helpreport->tanggal = $request->get('tanggal');
        $new_helpreport->alamat = $request->get('alamat');
        $new_helpreport->jenis_kerusakan = $request->get('jenis_kerusakan');
        $new_helpreport->jenis_bantuan = $request->get('jenis_bantuan');
        $new_helpreport->telepon = $request->get('telepon');
        $new_helpreport->keterangan = $request->get('keterangan');
        
        $foto = $request->file('foto');
            if($foto){
                $foto_path = $foto->store('helpreport-fotos', 'public');
                $new_helpreport->foto = $foto_path;
        }
        $new_helpreport->latitude = $request->get('latitude');
        $new_helpreport->longitude = $request->get('longitude');
        $new_helpreport->status = $request->get('status');

        $new_helpreport->user_id = \Auth::user()->id;
        $new_helpreport->created_by = \Auth::user()->id;
        $new_helpreport->save();

        return redirect()->route('helpreports.index')->with('status', 'Data laporan bantuan telah berhasil dibuat');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $helpreport = \App\Helpreport::findOrFail($id);

        return view('helpreports.show', ['helpreport' => $helpreport]);
 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $helpreport_to_edit = \App\Helpreport::findOrFail($id);
        
        return view('helpreports.edit', ['helpreport' => $helpreport_to_edit]);
  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $helpreport = \App\Helpreport::findOrFail($id);

        $helpreport->tanggal = $request->get('tanggal');
        $helpreport->alamat = $request->get('alamat');
        $helpreport->jenis_kerusakan = $request->get('jenis_kerusakan');
        $helpreport->jenis_bantuan = $request->get('jenis_bantuan');
        $helpreport->telepon = $request->get('telepon');
        $helpreport->keterangan = $request->get('keterangan');

        $new_foto = $request->file('foto');

        if($new_foto){
            if($helpreport->foto && file_exists(storage_path('app/public/' . $helpreport->foto))){
            \Storage::delete('public/'. $helpreport->foto);
        }
        $new_foto_path = $new_foto->store('helpreport-fotos', 'public');
        
        $helpreport->foto = $new_foto_path;
        }

        $helpreport->latitude = $request->get('latitude');
        $helpreport->longitude = $request->get('longitude');
        $helpreport->status = $request->get('status');

        $helpreport->updated_by = \Auth::user()->id;

        $helpreport->save();

        return redirect()->route('helpreports.index', ['id'=>$helpreport->id])->with('status', 'Laporan bantuan berhasil diperbarui');
   
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $helpreport = \App\Helpreport::findOrFail($id);

        $helpreport->delete();

        return redirect()->route('helpreports.index')->with('status', 'Laporan telah diarsipkan');
  
    }

    public function trash(){
        $deleted_helpreport = \App\Helpreport::onlyTrashed()->paginate(10);
        
        return view('helpreports.trash', ['helpreports' => $deleted_helpreport]);
    }

    public function restore($id){
        $helpreport = \App\Helpreport::withTrashed()->findOrFail($id);
        
        if($helpreport->trashed()){
            $helpreport->restore();
        } else {
            return redirect()->route('helpreports.index')->with('status', 'Laporan tidak ada di data arsip');
        }

        return redirect()->route('helpreports.index')->with('status', 'Laporan telah berhasil direstore');
    }

    public function deletePermanent($id){
        $helpreport = \App\Helpreport::withTrashed()->findOrFail($id);
        
        if(!$helpreport->trashed()){
            return redirect()->route('helpreports.index')->with('status', 'Laporan aktif, Tidak bisa hapus permanen!');
        } else {
            $helpreport->forceDelete();
            return redirect()->route('helpreports.index')->with('status', 'Laporan telah berhasil dihapus permanen');
        }
    }
}

resources/views/helpreports/create.blade.php
@extends("layouts.global")
@section("title") Tambah Data Laporan Bantuan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10" action="{{route('helpreports.store')}}"
            method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <div class="form-group">
                    <label for="tanggal">Tanggal Laporan</label>
                    <input type="date" class="form-control" id="tanggal" name="tanggal" placeholder="Masukkan tanggal">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat Laporan </label>
                    <input type="text" class="form-control" id="alamat" name="alamat" placeholder="Masukkan alamat">
                </div>
                <div class="form-group">
                    <label for="jenis_kerusakan">Jenis Kerusakan </label>
                    <input type="text" class="form-control" id="jenis_kerusakan" name="jenis_kerusakan" placeholder="Masukkan jenis kerusakan">
                </div>
                <div class="form-group">
                    <label for="jenis_bantuan">Jenis Bantuan </label>
                    <input type="text" class="form-control" id="jenis_bantuan" name="jenis_bantuan" placeholder="Masukkan jenis bantuan">
                </div>
                <div class="form-group">
                    <label for="telepon">Telepon</label>
                    <input type="text" class="form-control" id="telepon" name="telepon" placeholder="Masukkan nomor telepon">
                </div>
                <div class="form-group">
                    <label for="keterangan">Keterangan</label>
                    <input type="text" class="form-control" id="keterangan" name="keterangan" placeholder="Masukkan keterangan">
                </div>
                <div class="form-group">
                    <label for="foto">Foto</label>
                    <input type="file" class="form-control" id="foto" name="foto" placeholder="Foto">
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input type="text" class="form-control" id="latitude" name="latitude"
                        placeholder="Masukkan posisi latitude Laporan Banjir">
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input type="text" class="form-control" id="longitude" name="longitude"
                        placeholder="Masukkan posisi longitude Laporan Banjir">
                </div>
                <div class="form-group">
                <label for="status">Status</label><br>
                <select class="form-control" name="status" id="status">
                    <option value="BARU">BARU</option>
                    <option value="PROSES">PROSES</option>
                    <option value="SELESAI">SELESAI</option>
                    <option value="CANCEL">CANCEL</option>
                </select>
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/helpreports/edit.blade.php
@extends("layouts.global")
@section("title") Edit Data Laporan Banjir @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10"
            action="{{route('helpreports.update', ['helpreport'=>$helpreport->id])}}" method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <input type="hidden" value="PUT" name="_method">
                <div class="form-group">
                    <label for="tanggal">Tanggal Laporan</label>
                    <input value="{{$helpreport->tanggal}}" type="date" class="form-control" id="tanggal" name="tanggal"
                        placeholder="Masukkan tanggal">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat Laporan</label>
                    <input value="{{$helpreport->alamat}}" type="text" class="form-control" id="alamat" name="alamat"
                        placeholder="Masukkan Alamat">
                </div>
                <div class="form-group">
                    <label for="jenis_kerusakan">Jenis Kerusakan</label>
                    <input value="{{$helpreport->jenis_kerusakan}}" type="text" class="form-control" id="jenis_kerusakan" name="jenis_kerusakan"
                        placeholder="Masukkan jenis kerusakan">
                </div>
                <div class="form-group">
                    <label for="jenis_bantuan">Alamat Laporan</label>
                    <input value="{{$helpreport->jenis_bantuan}}" type="text" class="form-control" id="jenis_bantuan" name="jenis_bantuan"
                        placeholder="Masukkan jenis bantuan">
                </div>
                <div class="form-group">
                    <label for="telepon">Alamat Laporan</label>
                    <input value="{{$helpreport->telepon}}" type="text" class="form-control" id="telepon" name="telepon"
                        placeholder="Masukkan nomor telepon">
                </div>
                <div class="form-group">
                    <label for="keterangan">Keterangan</label>
                    <input value="{{$helpreport->keterangan}}" type="text" class="form-control" id="keterangan" name="keterangan"
                        placeholder="Masukkan keterangan">
                </div>
                <label for="foto">Foto</label><br>
                <small class="text-muted">Foto Awal</small><br>
                @if($helpreport->foto)
                <img src="{{asset('storage/' . $helpreport->foto)}}" width="50px" />
                @endif
                <br><br>
                <input type="file" class="form-control" name="foto">
                <small class="text-muted">Kosongkan jika tidak ingin mengubah
                    Foto</small>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input value="{{$helpreport->latitude}}" type="text" class="form-control" id="latitude" name="latitude"
                        placeholder="Masukkan posisi latitude Desa">
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input value="{{$helpreport->longitude}}" type="text" class="form-control" id="longitude"
                        name="longitude" placeholder="Masukkan posisi longitude Desa">
                </div>
                <div class="form-group">
                <label for="status">Status</label><br>
                <select class="form-control" name="status" id="status">
                    <option {{$helpreport->status == "BARU" ? "selected" : ""}} value="BARU">BARU</option>
                    <option {{$helpreport->status == "PROSES" ? "selected" : ""}} value="PROSES">PROSES</option>
                    <option {{$helpreport->status == "SELESAI" ? "selected" : ""}} value="SELESAI">SELESAI</option>
                    <option {{$helpreport->status == "CANCEL" ? "selected" : ""}} value="CANCEL">CANCEL</option>
                </select>
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Edit</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/helpreports/index.blade.php
@extends("layouts.global")
@section("title") Data Laporan Bantuan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Data Laporan Bantuan</h1>
            </div><br><br>
            <div class="col-sm-10">
            @if (Auth::user()->role==2)
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('helpreports.index')}}">Data Aktif</a></li>
                    <li class="breadcrumb-item"><a class="{{Request::get('status') == 'baru' ?'active' : '' }}"
                            href="{{route('helpreports.index', ['status' =>'baru'])}}">Data Baru</a></li>
                    <li class="breadcrumb-item"><a class="{{Request::get('status') == 'proses' ? 'active' : '' }}"
                            href="{{route('helpreports.index', ['status' => 'proses'])}}">Data Diproses</a></li>
                    <li class="breadcrumb-item"><a class="{{Request::get('status') == 'selesai' ?'active' : '' }}"
                            href="{{route('helpreports.index', ['status' =>'selesai'])}}">Data Terverifikasi</a></li>
                    <li class="breadcrumb-item"><a class="{{Request::get('status') == 'cancel' ?'active' : '' }}"
                            href="{{route('helpreports.index', ['status' =>'cancel'])}}">Data Dicancel</a></li>
                    <li class="breadcrumb-item"><a class="{{Request::path() == 'helpreports/trash' ? 'active' :''}}"
                            href="{{route('helpreports.trash')}}">Data Arsip</a></li>
                </ol>
            @endif
            </div>
            <div class="col-sm-2 text-right">
            @if (Auth::user()->role==3)
                <a href="{{route('helpreports.create')}}" class="btn btn-primary btn-sm">Tambah</a>
            @endif
            </div>
        </div>
        @if(session('status'))
        <div class="alert">
            {{session('status')}}
        </div>
        @endif
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th><b>Nama Pelapor</b></th>
                                    <th><b>Tanggal</b></th>
                                    <th><b>Foto</b></th>
                                    <th><b>Status</b></th>
                                    <th><b>Opsi</b></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($helpreports as $helpreport)
                                <tr>
                                    <td>{{$helpreport->user['username']}}</td>
                                    <td>{{$helpreport->tanggal}}</td>
                                    <td> @if($helpreport->foto)
                                            <img src="{{asset('storage/' . $helpreport->foto)}}" width="100px" />
                                        @endif
                                    </td>
                                    <td>
                                        @if($helpreport->status == "BARU")
                                        <span class="badge bg-warning text-light">{{$helpreport->status}}</span>
                                        @elseif($helpreport->status == "PROSES")
                                        <span class="badge bg-info text-light">{{$helpreport->status}}
                                        </span>
                                        @elseif($helpreport->status == "SELESAI")
                                        <span class="badge bg-success text-light">{{$helpreport->status}}</span>
                                        @elseif($helpreport->status == "CANCEL")
                                        <span class="badge bg-dark text-light">{{$helpreport->status}}
                                        </span>
                                        @endif
                                    </td>
                                    <td>
                                        <a class="btn btn-primary btn-sm"
                                            href="{{route('helpreports.edit',['helpreport'=>$helpreport->id])}}">Edit</a>
                                        <a class="btn btn-success btn-sm"
                                            href="{{route('helpreports.show',['helpreport'=>$helpreport->id])}}">Info</a>
                                        <form
                                            onsubmit="return confirm('Apakah Anda yakin ingin mengarsipkan data ini ?')"
                                            class="d-inline"
                                            action="{{route('helpreports.destroy', ['helpreport' => $helpreport->id ])}}"
                                            method="POST">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="submit" value="Arsip" class="btn btn-warning btn-sm">
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colSpan="10">
                                        {{$helpreports->appends(Request::all())->links()}}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/helpreports/show.blade.php
@extends("layouts.global")
@section("title") Detail Laporan Bantuan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>{{$helpreport->alamat}}</h1>
            </div><br><br>

        </div>
        @if(session('status'))
        <div class="alert">
            {{session('status')}}
        </div>
        @endif
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">          
                <div class="card mx-auto ">
                    <div id="mapid" style="width: 1000px; height: 350px">
                        <script>
                            var mymap = L.map('mapid').setView([-7.118736, 112.416550], 13);
                            L.tileLayer(
                                'https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                                    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                                        '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                                        'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                                    id: 'mapbox/streets-v11',
                                }).addTo(mymap);

                            L.marker([{{$helpreport->latitude}},{{$helpreport->longitude}}]).addTo(mymap)
                                .bindPopup('Tanggal Kejadian : {{$helpreport->tanggal}}, <br> Pelapor : {{$helpreport->user->name}}, <br> Alamat : {{$helpreport->alamat}}, <br> Jenis Kerusakan : {{$helpreport->jenis_kerusakan}}, <br> Jenis Bantuan : {{$helpreport->jenis_bantuan}}, <br> Telepon : {{$helpreport->telepon}}, <br> Keterangan : {{$helpreport->keterangan}}')
                                .openPopup();
                        </script>
                    </div>
                </div>
        </div>
    </div>
</section>
@endsection