routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/admin', 'AdminController@index')->name('admin')->middleware('admin');
Route::get('/operator', 'OperatorController@index')->name('operator')->middleware('operator');
Route::get('/lapor', 'LaporController@index')->name('lapor')->middleware('lapor');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource("users", "UserController");

Route::get('/subdistricts/trash', 'SubdistrictController@trash')->name('subdistricts.trash');
Route::get('/subdistricts/{id}/restore', 'SubdistrictController@restore')->name('subdistricts.restore');
Route::delete('/subdistricts/{id}/delete-permanent','SubdistrictController@deletePermanent')->name('subdistricts.delete-permanent');
Route::get('/ajax/subdistricts/search','SubdistrictController@ajaxSearch');
Route::resource("subdistricts", "SubdistrictController");

Route::get('/cari', 'Select2Controller@loadData');
Route::get('/villages/trash', 'VillageController@trash')->name('villages.trash');
Route::get('/villages/{id}/restore', 'VillageController@restore')->name('villages.restore');
Route::delete('/villages/{id}/delete-permanent','VillageController@deletePermanent')->name('villages.delete-permanent');
Route::resource('villages', 'VillageController');

Route::get('/floodreports/trash', 'FloodreportController@trash')->name('floodreports.trash');
Route::get('/floodreports/{id}/restore', 'FloodreportController@restore')->name('floodreports.restore');
Route::delete('/floodreports/{id}/delete-permanent','FloodreportController@deletePermanent')->name('floodreports.delete-permanent');
Route::resource('floodreports', 'FloodreportController');

Route::get('/helpreports/trash', 'HelpreportController@trash')->name('helpreports.trash');
Route::get('/helpreports/{id}/restore', 'HelpreportController@restore')->name('helpreports.restore');
Route::delete('/helpreports/{id}/delete-permanent','HelpreportController@deletePermanent')->name('helpreports.delete-permanent');
Route::resource('helpreports', 'HelpreportController');

Route::get('/floodhistories/trash', 'FloodhistoryController@trash')->name('floodhistories.trash');
Route::get('/floodhistories/{id}/restore', 'FloodhistoryController@restore')->name('floodhistories.restore');
Route::delete('/floodhistories/{id}/delete-permanent','FloodhistoryController@deletePermanent')->name('floodhistories.delete-permanent');
Route::resource('floodhistories', 'FloodhistoryController');

Route::get('/posts/trash', 'PostController@trash')->name('posts.trash');
Route::get('/posts/{id}/restore', 'PostController@restore')->name('posts.restore');
Route::delete('/posts/{id}/delete-permanent','PostController@deletePermanent')->name('posts.delete-permanent');
Route::resource('posts', 'PostController');

app/Subdistrict.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Subdistrict extends Model
{
    protected $table = 'subdistricts';

    use SoftDeletes;

    public function villages(){
        return $this->hasMany('App\Village');
    }
    
}

app/Http/Controllers/SubdistrictController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class SubdistrictController extends Controller
{

    public function __construct(){
        $this->middleware(function($request, $next){
            if(Gate::allows('manage-admin')) return $next($request);
            abort(403, 'Anda tidak memiliki cukup hak akses');
            });
        }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subdistricts = \App\Subdistrict::paginate(10);
        
        return view('subdistricts.index', ['subdistricts' => $subdistricts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subdistricts.create');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validation = \Validator::make($request->all(),[
            "name" => "required",
            "latitude" => "required",
            "longitude" => "required",
            ])->validate();

        $maxId = \App\Subdistrict::max('id');

        $new_subdistrict = new \App\Subdistrict;

        $new_subdistrict->id = $maxId + 1;
        $new_subdistrict->name = $request->get('name');
        $new_subdistrict->longitude = $request->get('longitude');
        $new_subdistrict->latitude = $request->get('latitude');

        $new_subdistrict->created_by = \Auth::user()->id;

        $new_subdistrict->save();

        return redirect()->route('subdistricts.index')->with('status', 'Data kecamatan telah berhasil ditambah'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subdistrict_to_edit = \App\Subdistrict::findOrFail($id);
        
        return view('subdistricts.edit', ['subdistrict' => $subdistrict_to_edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->get('name');
        $longitude = $request->get('longitude');
        $latitude = $request->get('latitude');

        $subdistrict = \App\Subdistrict::findOrFail($id);

        $subdistrict->name = $name;
        $subdistrict->longitude = $longitude;
        $subdistrict->latitude = $latitude;

        $subdistrict->updated_by = \Auth::user()->id;

        $subdistrict->save();
        
        return redirect()->route('subdistricts.index', ['subdistrict' => $id])->with('status', 'Data Kecamatan telah berhasil diedit');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subdistrict = \App\Subdistrict::findOrFail($id);

        $subdistrict->delete();

        return redirect()->route('subdistricts.index')->with('status', 'Data kecamatan berhasil diarsipkan');

    }

    public function trash(){
        $deleted_subdistrict = \App\Subdistrict::onlyTrashed()->paginate(10);
        
        return view('subdistricts.trash', ['subdistricts' => $deleted_subdistrict]);
    }

    public function restore($id){
        $subdistrict = \App\Subdistrict::withTrashed()->findOrFail($id);
        
        if($subdistrict->trashed()){
            $subdistrict->restore();
        } else {
            return redirect()->route('subdistricts.index')->with('status', 'Data kecamatan tidak ada di trash');
        }

        return redirect()->route('subdistricts.trash')->with('status', 'Data kecamatan telah berhasil direstore');
    }

    public function deletePermanent($id){
        $subdistrict = \App\Subdistrict::withTrashed()->findOrFail($id);
        
        if(!$subdistrict->trashed()){
            return redirect()->route('subdistricts.index')->with('status', 'Data kecamatan aktif, Tidak bisa hapus permanen!');
        } else {
            $subdistrict->forceDelete();
            return redirect()->route('subdistricts.index')->with('status', 'Data kecamatan telah berhasil dihapus permanen');
        }
    }

   
}

resources/views/subdistricts/create.blade.php
@extends("layouts.global")
@section("title") Tambah Data Kecamatan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10" action="{{route('subdistricts.store')}}"
            method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <div class="form-group">
                    <label for="name">Nama Kecamatan</label>
                    <input value="{{old('name')}}"
                        class="form-control {{$errors->first('name') ? "is-invalid" : ""}}" placeholder="Masukkan Nama Kecamatan"
                        type="text" name="name" id="name" />
                    <div class="invalid-feedback">
                        {{$errors->first('name')}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                        <input value="{{old('latitude')}}" class="form-control {{$errors->first('latitude') ? "is-invalid" : ""}}"
                        placeholder="Masukkan posisi latitude kecamatan" type="text" name="latitude" id="latitude" />
                    <div class="invalid-feedback">
                        {{$errors->first('latitude')}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                        <input value="{{old('longitude')}}" class="form-control {{$errors->first('longitude') ? "is-invalid" : ""}}"
                        placeholder="Masukkan posisi longitude kecamatan" type="text" name="longitude" id="longitude" />
                    <div class="invalid-feedback">
                        {{$errors->first('longitude')}}
                    </div> 
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Simpan</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/subdistricts/edit.blade.php
@extends("layouts.global")
@section("title") Edit Data Kecamatan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2"> 
        </div>     
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <form enctype="multipart/form-data" class="bg-white shadow-sm p-10"
            action="{{route('subdistricts.update', ['subdistrict'=>$subdistrict->id])}}" method="POST">
            <div class="card-body table-responsive p-10">
                @csrf
                <input type="hidden" value="PUT" name="_method">
                <div class="form-group">
                    <label for="name">Nama Kecamatan</label>
                    <input value="{{$subdistrict->name}}" type="text" class="form-control" id="name" name="name"
                        placeholder="Masukkan Nama Kecamatan">
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input value="{{$subdistrict->latitude}}" type="text" class="form-control" id="latitude"
                        name="latitude" placeholder="Masukkan posisi latitude kecamatan">
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input value="{{$subdistrict->longitude}}" type="text" class="form-control" id="longitude"
                        name="longitude" placeholder="Masukkan posisi longitude kecamatan">
                </div>
                <button type="submit" value="Save" class="btn btn-primary">Edit</button>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/subdistricts/index.blade.php
@extends("layouts.global")
@section("title") Data Kecamatan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Data Kecamatan</h1>
            </div><br><br>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item active"><a href="{{route('subdistricts.index')}}">Data Aktif</a></li>
                    <li class="breadcrumb-item"><a href="{{route('subdistricts.trash')}}">Data Arsip</a></li>
                </ol>
            </div>
            <div class="col-sm-6 text-right">
                <a href="{{route('subdistricts.create')}}" class="btn btn-primary btn-sm">Tambah</a>
            </div>
        </div>
        @if(session('status'))
        <div class="alert">
            {{session('status')}}
        </div>
        @endif
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">

                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Nama subdistrict</th>
                                    <th>Latitude</th>
                                    <th>Longitude</th>
                                    <th>Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($subdistricts as $subdistrict)
                                <tr>
                                    <td>{{$subdistrict->name}}</td>
                                    <td>{{$subdistrict->latitude}}</td>
                                    <td>{{$subdistrict->longitude}}</td>
                                    <td>
                                        <a class="btn btn-primary btn-sm"
                                            href="{{route('subdistricts.edit',['subdistrict'=>$subdistrict->id])}}">Edit</a>
                                        <form
                                            onsubmit="return confirm('Apakah Anda yakin ingin mengarsipkan data ini ?')"
                                            class="d-inline"
                                            action="{{route('subdistricts.destroy', ['subdistrict' => $subdistrict->id ])}}"
                                            method="POST">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="submit" value="Arsip" class="btn btn-warning btn-sm">
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colSpan="10">
                                        {{$subdistricts->appends(Request::all())->links()}}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/subdistricts/trash.blade.php
@extends("layouts.global")
@section("title") Data Arsip Kecamatan @endsection
@section("content")
<section class="content-header">
    <div class="container-fluid">
        <div class="row m-2 ">
            <div class="col-lg-12 text-center">
                <h1>Data Desa</h1>
            </div><br><br>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="{{route('subdistricts.index')}}">Data Aktif</a></li>
                    <li class="breadcrumb-item active"><a href="{{route('subdistricts.trash')}}">Data Arsip</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body table-responsive p-0">

                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Nama Kecamatan</th>
                                    <th>Latitude</th>
                                    <th>Longitude</th>
                                    <th>Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($subdistricts as $subdistrict)
                                <tr>
                                    <td>{{$subdistrict->name}}</td>
                                    <td>{{$subdistrict->latitude}}</td>
                                    <td>{{$subdistrict->longitude}}</td>
                                    <td>
                                        <a href="{{route('subdistricts.restore', ['id' => $subdistrict->id])}}"
                                            class="btn btn-success btn-sm">Restore</a>
                                        <form class="d-inline"
                                            action="{{route('subdistricts.delete-permanent', ['id' => $subdistrict->id])}}"
                                            method="POST"
                                            onsubmit="return confirm('Apakah Anda yakin ingin menghapus data ini secara permanen?')">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE" />
                                            <input type="submit" class="btn btn-danger btn-sm" value="Delete" />
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colSpan="10">
                                        {{$subdistricts->appends(Request::all())->links()}}
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
@endsection